version: '3.5'

services:

  angular-server:
    image: ${REPOSITORY}/${IMAGE}:${TAG}
    ports:
      - 4201:80
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
