version: '3.5'

services:
  frontend:
    image: docker.nexus.archi-lab.io/archilab/coalbase-frontend
    ports:
    - 4201:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
